services:
  db:
    image: postgres:16.2
    container_name: filepriv_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filepriv_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/backend/databasesql.sh:/docker-entrypoint-initdb.d/databasesql.sh
volumes:
  pgdata:
